services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - 3001:3001
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    healthcheck:
      test: wget -qO- http://localhost:3001/api/v1/status
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
